### ISSUE TITLE
GSA Captcha Breaker Intergration

### ISSUE THREAD

**Issue by DapetJackpot** [rcarubbi/Carubbi.CaptchaBreaker#1]
How do you integrate this with GSA Captcha Breaker?

**Comment by rcarubbi** [comment]
Hi, it's a TCP communication, you can see it here: https://github.com/rcarubbi/Carubbi.CaptchaBreaker/blob/master/Carubbi.CaptchaBreaker/Implementation/GSACaptchaBreaker.cs

**Comment by rcarubbi** [comment]
Also, I exposed it as a HTTP service forwarding the request in order to access it externally. You can check it on the following link:
https://github.com/rcarubbi/Carubbi.CaptchaBreaker/blob/master/Carubbi.CaptchaBreaker/Implementation/RemoteGSACaptchaBreaker.cs

**Comment by rcarubbi** [comment]
However, I've implemented it ages ago so it would be worth double-checking if it's still working with the latest GSA Captcha Breaker version

**Comment by DapetJackpot** [comment]
Hi, I see. I will try it out. Thanks a lot!

**Comment by rcarubbi** [comment]
Please let me know if you could get it working so I can close the issue

**Comment by rcarubbi** [comment]
Closed by lack of activity
